name: CQBot_Run
on: push
jobs:
  Start1:
    runs-on: ubuntu-latest
    steps:
    - name: 运行
      run: |
            sudo git clone https://github.com/yi985432/CQBot
            cd CQBot
            sudo sh ./run.sh
